#!/bin/sh /etc/rc.common

USE_PROCD=1
START=19
STOP=89

PROG=/usr/sbin/failsafe-dns-proxy
CONFIG=/etc/config/failsafe-dns-proxy

start_service() {
	local enabled
	config_load failsafe-dns-proxy
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 0

	"$PROG" check-config --config "$CONFIG" || return 1

	procd_open_instance
	procd_set_param command "$PROG" run --config "$CONFIG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param file "$CONFIG"
	procd_set_param limits nofile="1024 1024"
	procd_close_instance
}

reload_service() {
	"$PROG" check-config --config "$CONFIG" || return 1
	procd_send_signal failsafe-dns-proxy '' HUP
}

service_triggers() {
	procd_add_reload_trigger failsafe-dns-proxy
}
